apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  namespace: discord-db
spec:
  selector:
   app: discord-postgresql-pod
  ports:
  - name: http
    protocol: TCP
    port: 5432
    targetPort: 5432
  type: LoadBalancer