apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
  namespace: discord-db
spec:
  storageClassName: postgresql-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi